version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: recipe-storage-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: recipe_storage
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
